### ISSUE TITLE
WalletConnect is seems that version 1.6.2 has not been released to cocoapods yet

### ISSUE THREAD

**Issue by chuck0930** [WalletConnect/WalletConnectSwift#116]
WalletConnect doesn't seem to have version 1.6.2 released on cocoapods yet. 
It's deployed on SPM, but not on cocoapods. Please check it out and release it.

**Comment by DmitryBespalov** [comment]
Fixed in [v1.7.0](https://github.com/WalletConnect/WalletConnectSwift/releases/tag/1.7.0)
