### ISSUE TITLE
Hex format of personal_sign may be incorrect

### ISSUE THREAD

**Issue by Cydie** [WalletConnect/WalletConnectSwift#119]
Is there any particular reason why 0x prefix is not included when using personal_sign?

The Valora wallet for example will only respond to personal_sign messages that are formated with the 0x prefix, otherwise personal_sign will result in a failure.

For me the 0x prefix seems kind-of like a standard, even the geth documentation shows that message data is 0x prefixed:
https://geth.ethereum.org/docs/rpc/ns-personal

**Comment by DmitryBespalov** [comment]
hm, we'll check this out, but it does seem strange. Are you implementing wallet or a dapp? Can you share more details about the issue?

**Comment by Cydie** [comment]
Thank you

I am implementing it as a dapp, in practice it will be part of a library/SDK that will have a WalletConnect dependency.

Basically the issue is that some wallets like MetaMask do accept data in personal_sign that are not prefixed with 0x, and in case of MetaMask by taking a glance at their source code, seems like even messages that are not converted to hex are accepted as valid inputs too, because they have an error correction step for message data. When the input is not hex formatted or not prefixed, they take the input and convert it to a properly formatted hex data.

You can check how they implemented their message data correcting code [here](https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/util.ts#L481)

(If you'd like to take a look at the full flow of their personal_sign implementation, here is how it goes step by step till it reaches the error correcting part [1](https://github.com/MetaMask/metamask-mobile/blob/dba76d52d72ccaa354f132f8f33038716116996f/app/core/RPCMethods/RPCMethodMiddleware.ts#L350), [2](https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/message-manager/PersonalMessageManager.ts#L74), [3](https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/message-manager/PersonalMessageManager.ts#L114), [4](https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/util.ts#L481) ) 

Other wallets for example Valora will enforce a strict formatting for the input and won't try correcting messages that are not following the message data format, it will just fail during the signing process.

Here is the [personal_sign](https://github.com/celo-org/celo-monorepo/blob/48e389c609c6ca9dd08a40ba9a5248ecc9764c11/packages/sdk/wallets/wallet-base/src/wallet-base.ts#L96) implementation and the related [isHexString](https://github.com/celo-org/celo-monorepo/blob/48e389c609c6ca9dd08a40ba9a5248ecc9764c11/packages/sdk/base/src/address.ts#L22) check

**Comment by DmitryBespalov** [comment]
Thanks for sharing! I'll take a look. 

On a side note, when we were implementing the access to wallets, after testing 130 wallets from the wallet connect iOS registry, I found that only a handful of them actually work, i.e. receive connection and are able to make a transaction.

**Comment by Cydie** [comment]
This is basically our goal as well. Query the registry, link/launch wallets, connect and sign our data with them.

There are some wallets and networks which are higher on the priority list for us for now but it would be preferable to have a solution that does not depend from wallet specific codes, that's why WalletConnect seemed to be the optimal solution.

Why do you think the number of working, compatible wallets on iOS was so low? Is it because they neglect iOS compatibility (many wallets are cross platform apps), or just generally not following WalletConnect specs?

What was your approach dealing with these incompatible wallets? Did you just exclude them from being supported by your app/library (if this was in scope of what you worked on)? 
Testing all those 130 wallets sounds fun 😄
