### ISSUE TITLE
Missing or invalid socket data

### ISSUE THREAD

**Issue by pharms-eth** [WalletConnect/WalletConnectSwift#122]
I am trying to setup the connection, when I scan a QR code I end up getting the message "Missing or invalid socket data"
additionally the delegate methods do not get called

**Comment by pharms-eth** [comment]
I just ran the sample app and got the same error

**Comment by pharms-eth** [comment]
I have determined the Missing data response comes from the request JSON: 
{"payload":"","topic":"44e88c86-502a-4c24-8687-72b760951f08","type":"sub"}

**Comment by pharms-eth** [comment]
it is sending it to https://n.bridge.walletconnect.org
it is part of the connection flow
I don't see any missing settings on my end, so unsure what your API is expecting

**Comment by DmitryBespalov** [comment]
Hi, please use the library version 1.6.0 while we'll be working on a new update to fix the ongoing issues.

For the working example of the wallet connect in a published app, you can browse the code starting from
https://github.com/safe-global/safe-ios/blob/main/Multisig/UI/WalletConnect/Server/WalletConnectServerController.swift

**Comment by pharms-eth** [comment]
https://github.com/pharms-eth/WalletConnectSwift/commit/1d6942b44c4672af80300c8689da6eb00adb528b

**Comment by DmitryBespalov** [comment]
@pharms-eth please check the latest `master` branch, we've removed Starscream in #124

**Comment by DmitryBespalov** [comment]
Fixed in [v1.7.0](https://github.com/WalletConnect/WalletConnectSwift/releases/tag/1.7.0)

The sample apps will be updated a bit later
