### ISSUE TITLE
Kotlin/Android version

### ISSUE THREAD

**Issue by jemshit** [WalletConnect/WalletConnectSwift#123]
Hi,
is there a Kotlin/Android version of this library?

These seems inactive/incomplete compared to Swift library:
https://github.com/WalletConnect/kotlin-walletconnect-lib/
https://github.com/WalletConnect/wallet-connect-kotlin/
https://github.com/trustwallet/wallet-connect-kotlin/

**Comment by DmitryBespalov** [comment]
Hi @jemshit, our app was using https://github.com/WalletConnect/kotlin-walletconnect-lib/ on Android and someone from our team contributed to it, however, I don't have a direct experience with an Android implementation of the wallet connect

**Comment by jemshit** [comment]
Thank you

**Comment by jemshit** [comment]
I wrote my own lib, you can give a try and give feedback
https://github.com/jemshit/WalletConnect
