### ISSUE TITLE
Logs can't be disabled, not even in release mode

### ISSUE THREAD

**Issue by CassiusPacheco** [WalletConnect/WalletConnectSwift#134]
The [custom logging mechanism](https://github.com/WalletConnect/WalletConnectSwift/blob/master/Sources/PublicInterface/Logger.swift) is quite simple but also verbose and naive, not allowing for granularity nor disabling it in release mode, which is critical since it might be leaking customers' information.

We could either simply add an option to disable it, so developers decide whether it's too noisy or not, plus disabling it by default for release mode, or implementing Apple's new-ish [Logger](https://developer.apple.com/documentation/os/logger)'s logging system, which is much more robust and aligned with the platform (only available for iOS 14+, so we'd still need to implement the simpler approach for iOS 13).

I'm happy to help with this. Do we have any preference?

**Comment by CassiusPacheco** [comment]
Closing this since the PR has been merged, even though it hasn't been released quite yet

**Comment by DmitryBespalov** [comment]
I'll test it first to see if the existing app works after the update
