### ISSUE TITLE
Is this repository still being maintained?

### ISSUE THREAD

**Issue by CassiusPacheco** [WalletConnect/WalletConnectSwift#139]
Hi there,

honest question. We've got some important Pull Requests opened, and I can see that the focus has been on the protocol v2, which was what I've been told on Discord.

I'd like to know officially, if possible, whether this has began to be deprecated in favour of v2 (which a lot of the main wallets don't implement yet, apparently?), and if a fork needs to be worked on for further support?

Regardless, **thanks heaps** for the work that's been done till now

**Comment by DmitryBespalov** [comment]
Hey, thanks for rising this issue. Reality is that I'm the only active maintainer on this repository now, and I have too much in a day job going on to attend to this repo, too. So, I'm coming back to it from time to time. 

WalletConnect team has built the v2 library and they want everyone to transition to it, but the wallets have to transition first, which means wallets have to support both v1 and v2 libraries before dapps have transitioned to v2.

In the meantime, I recommend you making a fork, making changes and use your fork in your app, and then submit the changes back to this repo.

I'll review the pull requests asap.

**Comment by CassiusPacheco** [comment]
I appreciate your effort @DmitryBespalov, thank you again for your time
