### ISSUE TITLE
Lowering minimum OS version to 11-11.3?

### ISSUE THREAD

**Issue by DarthMike** [WalletConnect/WalletConnectSwift#22]
Hello,

is it possible to lower minimum requirement of library to iOS 11, or 11.3?

**Comment by sche** [comment]
Hi @DarthMike 
Probably yes. You could make a fork and change the minimum iOS version - it should work.

**Comment by DarthMike** [comment]
Thanks. Happy to contribute to main, I can work on a PR and let you know.

**Comment by DarthMike** [comment]
@sche See #23
