### ISSUE TITLE
Deeplinking not working 

### ISSUE THREAD

**Issue by daihovey** [WalletConnect/WalletConnectSwift#33]
Using the `ClientApp` in ExampleApps to connect is not working correctly with the two wallets I have installed on device (Metamask & Rainbow)

If I force it show the QRCode, screenshot it, and then open Rainbow, the flow works. But the deeplinking just opens Metamask, but nothing happens within Metamask.

**Comment by daihovey** [comment]
I got a little further by encoding the uri 

```
@IBAction func connect(_ sender: Any) {
        let connectionUrl = walletConnect.connect()
        
        let customAllowedSet =  NSCharacterSet(charactersIn:"=\"#%/<>?@\\^`{|}:&").inverted
        
        guard let encoded = connectionUrl.addingPercentEncoding(withAllowedCharacters: customAllowedSet) else { fatalError("connectionUrl encoding failed") }
        
        let deepLinkUrl = "https://rnbwapp.com/wc?uri=" + encoded
                
        if let url = URL(string: deepLinkUrl), UIApplication.shared.canOpenURL(url) {
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        } else {
            handshakeController = HandshakeViewController.create(code: connectionUrl)
            present(handshakeController, animated: true)
        }
    }
```
which connects Rainbow correctly, but the Client App stays inactive.

Some differences in the WC data compared to Rainbow's:

* the id from the server app is a negative number
* peer id is lowercase vs uppercase
* ssl and description are missing on peerMeta
* rpcUrl is missing

**Comment by papanmanna** [comment]
@daihovey , rainbow connection is working after using your code. I have to open metamask app, How can I do that?

**Comment by daihovey** [comment]
@papanmanna try changing the `deepLinkUrl` to "https://metamask.app.link"

**Comment by Arcovv** [comment]
I used this to open MetaMask App: `metamask://wc?uri=`

You can see more in here:
https://github.com/MetaMask/metamask-mobile/blob/main/ios/MetaMask/Info.plist#L26
<img width="321" alt="image" src="https://user-images.githubusercontent.com/11262771/172733946-373fe8ba-0599-47de-b898-0c086dc61b34.png">
