### ISSUE TITLE
Crash into Server.failedToConnect

### ISSUE THREAD

**Issue by DtechLabs** [WalletConnect/WalletConnectSwift#38]
Hi,

I have a few crashes into the Server class cuz  you use force unwrap for weak var delegate

> public private(set) weak var delegate: ServerDelegate!

Please make it optional.  It allows avoiding a crash when delegate already destroeyed

**Comment by DmitryBespalov** [comment]
Hi @DtechLabs, thanks for reporting it. Would it be possible to share the crash report?

**Comment by DtechLabs** [comment]
@DmitryBespalov Sure!

Crashed: org.walletconnect.swift.connection-https://bridge.walletconnect.org-bf568ec5-4f6c-472f-98f1-1e6879027707
0  PlasmaPay                      0x10143ead0 Server.failedToConnect(_:) + 4301335248
1  PlasmaPay                      0x10144afa8 specialized WalletConnect.onDisconnect(from:error:) + 4301385640
2  PlasmaPay                      0x10141f994 partial apply for closure #2 in closure #1 in Bridge.listen(on:onConnect:onDisconnect:onTextReceive:) + 4301207956
3  PlasmaPay                      0x1014306c8 protocol witness for WebSocketDelegate.websocketDidDisconnect(socket:error:) in conformance WebSocketConnection + 4301276872
4  PlasmaPay                      0x10145b94c closure #1 in WebSocket.doDisconnect(_:) + 4301453644
5  PlasmaPay                      0x101450eec thunk for @escaping @callee_guaranteed () -> () + 4301410028
6  libdispatch.dylib              0x18d90724c _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x18d908db0 _dispatch_client_callout + 20
8  libdispatch.dylib              0x18d91010c _dispatch_lane_serial_drain + 580
9  libdispatch.dylib              0x18d910c5c _dispatch_lane_invoke + 408

**Comment by DmitryBespalov** [comment]
@DtechLabs I've released new version 1.3.1 with the fixes, please let me know if it helps

**Comment by DtechLabs** [comment]
@DmitryBespalov Great! Our next release will be soon.  I'll be monitoring it and let you know
