### ISSUE TITLE
Will this be supported for https://l2.mintr.synthetix.io/

### ISSUE THREAD

**Issue by mehranhydary** [WalletConnect/WalletConnectSwift#43]
Used WalletConnect on L1 to move some SNX into L2... now I can't do anything... please help!

**Comment by sche** [comment]
Hi @mehranhydary 
Could you please elaborate a bit more what exact issue are you experiencing?
If https://l2.mintr.synthetix.io/ does not support WalletConnect, I would recommend to contact Synthetix team support.

**Comment by mehranhydary** [comment]
Hi @sche - of course. So I went to the site and i can't use WalletConnect to connect my wallet into the app. I did talk to the Synthetix team but they mentioned that the teams working on wallets should be the ones implementing this...

![Screen Shot 2021-02-15 at 11 06 01 AM](https://user-images.githubusercontent.com/2007405/107969489-d9c39200-6f7d-11eb-99c3-715bb0438ae1.png)

**Comment by sche** [comment]
Hi @mehranhydary 
May be I am missing something, but probably they mean that WalletConnect protocol itself is missing some feature in this case? I just don't get why team allowed to use MetaMask, but not WalletConnect (which is a wallet agnostic protocol)
