### ISSUE TITLE
Open Metamask while transaction

### ISSUE THREAD

**Issue by Pavan-Unikwork** [WalletConnect/WalletConnectSwift#44]
I am connecting Metamask wallet from my app using WalletConnectSwift and get the wallet address successfully. (For connecting, the User is navigated to Metamask for connect)
But now I am trying to send_ethTransaction from my app, I want to redirect the Metamask app for approval same as connection flow.
How can I do it?

**Comment by DmitryBespalov** [comment]
Can you try this: send the request to the WalletConnect, and then open the metamask-specific / or "wc:" link with any host/uri  - the user has to just switch to the Metamask again, and the WalletConnect will work.

https://docs.walletconnect.org/mobile-linking some info on mobile linking, but your question is not addressed there

**Comment by Pavan-Unikwork** [comment]
> Can you try this: send the request to the WalletConnect, and then open the metamask-specific / or "wc:" link with any host/uri - the user has to just switch to the Metamask again, and the WalletConnect will work.
> 
> https://docs.walletconnect.org/mobile-linking some info on mobile linking, but your question is not addressed there

I have tried it.
I have open the Metamask with "wc:" link and on completion of opening the app I have triggered send_ethTransaction function but I am not getting any pop-up for approving transaction like connect wallet flow

**Comment by sche** [comment]
@Pavan-Unikwork are you using `eth_sendTransaction` of `Client` class?
If yes, then it is strange if Metamask can not get this request. It should work. You can check this prototype app where we used Metamask with `eth_sendTransaction` https://github.com/gnosis/gp-v2-swap-ios/blob/56112a9811e21e4da6de659309190130a395b340/Swap/Services/WalletService.swift#L160

**Comment by DmitryBespalov** [comment]
@Pavan-Unikwork I'm attaching the example WalletService class that we used in internal prototype (can't share the prototype because of API secrets in code 🤦 😊 ), maybe it would help you - please take a look at the `sendTransaction()` method.

The code is under MIT license.

[WalletService.swift.txt](https://github.com/WalletConnect/WalletConnectSwift/files/6021042/WalletService.swift.txt)

**Comment by Pavan-Unikwork** [comment]
Thank you guys.
It's work for me.
Thanks for the support.

**Comment by JulienLevallois** [comment]
Hey guys, Im connected to metamask, I have one active session and I want to call a method of one smartContract opening metamask. Do you have ideas? 
Thanks a lot

**Comment by JulienLevallois** [comment]
<img width="980" alt="Capture d’écran 2021-11-30 à 19 02 21" src="https://user-images.githubusercontent.com/5727223/144147433-75be72a7-d387-42d5-9ebf-4f28868b1bd2.png">
I think I have to use this method but I dont have any ideas of the transaction struct
