### ISSUE TITLE
SwiftUI with UIKit issue

### ISSUE THREAD

**Issue by Tahaylmz** [WalletConnect/WalletConnectSwift#47]
Hi, my name is Taha. I'm coding with SwiftUI. I choose to use WalletConnect library but looks like it was written in UIKit. How can i use this library in SwiftUI?

**Comment by DmitryBespalov** [comment]
Hi Taha, nice to meet you 👋 The library does not ship with any UI SDK library itself, but the demo projects are using UIKit.

I'll find an example with SwiftUI for you, please wait

**Comment by DmitryBespalov** [comment]
@Tahaylmz to clarify, you just need to see how to install the library in a SwiftUI-based project or you need complete example of creating a wallet & dapp using SwiftUI?

**Comment by DmitryBespalov** [comment]
Ok, so I reviewed the current code once again and I think the current library can be integrated, but you would need to write the interaction with it yourself. 

For this, I would implement the request handling inside a view model.

I can't provide you with any example code at the moment because I'm busy with other project

**Comment by DmitryBespalov** [comment]
You can add the library to Xcode project by adding it as a package - https://github.com/WalletConnect/WalletConnectSwift.git

**Comment by Tahaylmz** [comment]
Hi, sorry for being late. I trying to do SwiftUI and UIKit work together. Will there be a problem?

**Comment by Tahaylmz** [comment]
Am i change codes in this link? https://github.com/WalletConnect/WalletConnectSwift.git
Because there is no ViewControllers in SwiftUI.

**Comment by DmitryBespalov** [comment]
If you add that link as a package (here's [help doc](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app)), then you will get the library integrated in your app. 

If you are using cocoa pods, then add `pod 'WalletConnectSwift'` to your Podfile.

Please note that the library doesn't come with any UI, so you need to implement your UI yourself and connect it to the library.

Depending on what kind of app you use, you need to implement either ClientDelegate (if you're implementing a dapp side), or a ServerDelegate and RequestHandler protocols (if you're implementing a wallet).

**Comment by Tahaylmz** [comment]
Thank you so much, I'm trying right now.

**Comment by Tahaylmz** [comment]
static func create(code: String) -> HandshakeViewController {
        let storyboard = UIStoryboard(name: "Main", bundle: Bundle.main)
        let controller = storyboard.instantiateViewController(withIdentifier: "HandshakeViewController") as! HandshakeViewController
        controller.code = code
        return controller
    }
    
    
    Hi, how can i this lines of code edit for SwiftUI? No ViewControllers in SwiftUI, im confused.

**Comment by raspberry-hu** [comment]
> ```
> static func create(code: String) -> HandshakeViewController {
>     let storyboard = UIStoryboard(name: "Main", bundle: Bundle.main)
>     let controller = storyboard.instantiateViewController(withIdentifier: "HandshakeViewController") as! HandshakeViewController
>     controller.code = code
>     return controller
> }
> 
> 
> Hi, how can i this lines of code edit for SwiftUI? No ViewControllers in SwiftUI, im confused.
> ```

I also want to use WalletConnect in my SwiftUI App, but I do not find any demo, do you have some idea?
