### ISSUE TITLE
Connection failure on iOS 14.5

### ISSUE THREAD

**Issue by johnqh** [WalletConnect/WalletConnectSwift#49]
It works fine in 14.4, but on newly released 14.5, connection fails. Delegate's client(_ client: Client, didFailToConnect url: WCURL) gets called. It happens in both simulator and device.

**Comment by shuvayanrhymetech** [comment]
I want to connect metamask with this wallet connect sdk, its open metamsk with example client app but connection request pop up not open metamask. ios 14.3 and 14.5 both version device checking, it's not working. Kindly, please help.
