### ISSUE TITLE
Opening Trust Wallet from wallet connect showing 'Something went wrong'

### ISSUE THREAD

**Issue by Ashwanikumar88** [WalletConnect/WalletConnectSwift#52]
Was trying to use wallet connect to get account data from trust wallet, however the request sent from wallet connect doesn't seem to work, trust wallet opens a screen with Something went wrong.

Below is the URL thats being created and used to open Trust wallet:
wc:46278999-4477-46FF-88D1-947FADDC979B@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=127820ed39c533dcce56d33b6820cdceabe7692ed00094be492191199f027d39

Error Screenshot url : https://ibb.co/qy8cwzg
Any help would be highly appreciated.

**Comment by sche** [comment]
Example apps use deep linking for communicating with each other. TrustWallet and other wallets much better support universal links.
Here you can find an example how we build universal link that works for TrustWallet: https://github.com/gnosis/safe-ios/blob/d4301687ce0a84e6bab2de398948d980deef3873/Multisig/UI/WalletConnect/WalletConnectClientController.swift#L70
