### ISSUE TITLE
Question - how to use the client dapp lib to connect to a different wallet

### ISSUE THREAD

**Issue by Schwartz10** [WalletConnect/WalletConnectSwift#56]
Hey there! Sorry for throwing a noob question in here, but are there any examples of using the client library to connect to a different mobile wallet, like Rainbow wallet?

I can't seem to figure out how to configure the lib to work with servers other than the mock wallet supplied by this lib. I'm happy to submit a little PR to add a code snippet to the README as well once this question gets answered! 

Thank you for any help

**Comment by DmitryBespalov** [comment]
@Schwartz10 Hey, welcome 😄 Maybe you can take a look at this folder in gnosis safe repo: https://github.com/gnosis/safe-ios/tree/main/Multisig/UI/WalletConnect Currently supported wallets there are metamask, ledger live, rainbow and trust.

**Comment by sche** [comment]
How to select an installed wallet code example is here https://github.com/gnosis/safe-ios/blob/main/Multisig/UI/Settings/OwnerKeyManagement/WalletConnectOwnerKey/ConnectWalletViewController.swift
