### ISSUE TITLE
Server's delegate was nil when call 'didDisconnect' func in some cases

### ISSUE THREAD

**Issue by AlleniCode** [WalletConnect/WalletConnectSwift#66]
![QQ20210801-101158](https://user-images.githubusercontent.com/8855341/127756940-a5614e04-9364-4913-9497-a87d7bc67107.png)

**Comment by sche** [comment]
Please update the lib version. Delegate is optional in the latest version https://github.com/WalletConnect/WalletConnectSwift/blob/9297fba1901d93d68418ee1b761b27ae2410ef0c/Sources/PublicInterface/Server.swift#L127

Probably your implementation that is using this library releasing delegate at some point so it crashes here.

**Comment by AlleniCode** [comment]
OK, thank you very much! 👍

**Comment by AlleniCode** [comment]
@sche Pod updated?

`pod search 'WalletConnectSwift'`

```swift
-> WalletConnectSwift (1.3.1)
   A delightful way to integrate WalletConnect into your app.
   pod 'WalletConnectSwift', '~> 1.3.1'
   - Homepage: https://github.com/WalletConnect/WalletConnectSwift
   - Source:   https://github.com/WalletConnect/WalletConnectSwift.git
   - Versions: 1.3.1, 1.3.0, 1.2.0, 1.0.1, 1.0.0 [master repo]
```

**Comment by sche** [comment]
@AlleniCode no, the pod was not updated. Could you check now?

**Comment by AlleniCode** [comment]
Yeah, I have tested and it won't crash anymore.
