### ISSUE TITLE
Is it possible to connect to SafePal?

### ISSUE THREAD

**Issue by ChurikiTenna** [WalletConnect/WalletConnectSwift#67]
I have successfully connected to metamask, and rainbow etc... 
Is there anyway I can connect to safepal?

Thank you in advance.

**Comment by sche** [comment]
I never used SafePal. You can connect only to wallets that support the WalletConnect protocol. Please ask the SafePal team if they plan to support it.

**Comment by ChurikiTenna** [comment]
Thank your for a response!
I asked to SafePal, and they replied.

—-
Wallet connect is already avalaible so you can connect safepal to any web3 platform.

What you want to do through wallet connect exactly? Because wallet connect is to connect a wallet through a web3 porotocol, to an online website, so please give me directly the web3 compatible website that you want to use with wallet connect.
—-

It seems they already support it.
But i don’t really get what they mean…

**Comment by sche** [comment]
Hi @ChurikiTenna 
> I have successfully connected to metamask, and rainbow etc...
Is there anyway I can connect to safepal?

How did you connect rainbow? To what dApp are you trying to connect? Could you share some screenshots of what does not work for you?
Thank you!

**Comment by ChurikiTenna** [comment]
I have used the code below as a example to connect my client dapp to metamask, and rainbow etc…
https://github.com/gnosis/safe-ios/tree/main/Multisig/UI/WalletConnect

I could open safepal using deep link.
On the safepal side, it looks like the app is successfully connected.
But I doesn’t call didConnected Session method on my client dapp.

![321814F6-CBFB-4B24-B3A2-E34014B946A6](https://user-images.githubusercontent.com/52132649/128270303-c43c612b-feb5-4c71-b2ca-14143f882d6a.png)
![D3488BD7-3F53-4237-A830-0CFA605AABCC](https://user-images.githubusercontent.com/52132649/128270399-bc31437b-a627-4221-8d30-9250fa169551.jpeg)

**Comment by sche** [comment]
Yeah, there might be different reasons. Did you check in the console if there are any incoming messages from the SafePal app? Did you try to connect it via QR code? 
In the console, you should see messages like 
```
WC: ==> {"id":1628266387759940,"jsonrpc":"2.0","method":"wc_sessionRequest","params":[{"chainId":4,"peerId":"26E259ED-E43C-492F-88A8-B21D75BCD69C","peerMeta":{"description":"The most trusted platform to manage digital assets on Ethereum","icons":["https:\/\/gnosis-safe.io\/app\/favicon.ico"],"name":"Gnosis Safe","scheme":"gnosissafe","url":"https:\/\/gnosis-safe.io"}}]}

WC: <== {"id":1628266387759940,"jsonrpc":"2.0","result":{"accounts":["0xD...a"],"approved":true,"chainId":1,"networkId":0,"peerId":"6e707efe-60ce-47da-a4e0-8f69379c8828","peerMeta":{"description":"MetaMask Mobile app","icons":["https:\/\/raw.githubusercontent.com\/MetaMask\/brand-resources\/master\/SVG\/metamask-fox.svg"],"name":"MetaMask","ssl":true,"url":"https:\/\/metamask.io"},"rpcUrl":""}}
```

**Comment by ChurikiTenna** [comment]
Thank you for the reply!!

I see "WC: ==> {etc etc...." on the console, but "WC: <== {etc etc..." does not appear.
Tried to connect with QR code, but seems not working too...

**Comment by ChurikiTenna** [comment]
Update.

After I added safepal to LSApplicationQueriesSchemes, then connected to SafePal, following were shown on the console.

`WC: <== {"id":1628811177447783,"jsonrpc":"2.0","result":{"accounts":["0x895F0fb1F2355B6C91a0d3F4A06008c1348f1bF5"],"approved":true,"chainId":1,"peerId":"a0d194b8-5d33-4137-aae7-623e435cf4e0","peerMeta":{"description":null,"icons":null,"name":"SafePal Wallet","url":"https:\/\/www.isafepal.io"}}}`

But, still not called.

`func client(_ client: Client, didConnect session: Session)`

**Comment by ChurikiTenna** [comment]
Update.

After I connected to SafePal, and go back to my client app,
`didFailToConnect` was called, which called in the `catch` statement in `func handleHandshakeResponse`.

Decoding `Session.WalletInfo` seems to be throwing error there.
Setting `icons` field  in `struct ClientMeta` to optional, might solve the problem.

Thank you.

**Comment by sche** [comment]
Thank you @ChurikiTenna 
Usually, wallets send icons with their logo. I am a bit reluctant in doing all the fields as optional in all structs if some wallet decided not to send some data.
But you can create a new ticket related to it, and if we have some more demand on it from the community, we will make this change. For now, I would recommend asking the SafePal team to add this data.
