### ISSUE TITLE
Hello, can support version 4.0.4 of Starscream?

### ISSUE THREAD

**Issue by Lvykk** [WalletConnect/WalletConnectSwift#82]
Hello, I am currently experiencing a conflict with the Starscream library. When a library supports version 3, I will not be able to install it

**Comment by DmitryBespalov** [comment]
Hey, this is a known issue, we have 4 (sic!) prs open for that, it’ll be resolved till the end of this week.

**Comment by dustfire** [comment]
@DmitryBespalov did this ever got resolved? thank you

**Comment by DmitryBespalov** [comment]
@dustfire the dependencies are updated in 1.6.2, but now it seems there's issue with disconnecting the sessions after that update
