### ISSUE TITLE
Problem when connect with Trust Wallet

### ISSUE THREAD

**Issue by dhnghia22** [WalletConnect/WalletConnectSwift#83]
Hello.
I try to connect to Trust Wallet using connect function, i run example and got this alert from Trust Wallet

![IMG_0036](https://user-images.githubusercontent.com/20497888/140554314-b8e4bdfa-0f0d-41fb-b074-0146bd3429fe.PNG)

Connect via QR code seem to be working. How to fix this problem or maybe Trust Wallet is not accept connect via this function.

**Comment by dhnghia22** [comment]
Update: I found the problem is line:
`let deepLinkUrl = "wc://wc?uri=\(connectionUrl)"`
no need to add prefix in to connectionUrl, and we need to wait client connected before open url to open trust wallet.

I have 1 more question, how to set default network when connect ?

**Comment by a-markovsky** [comment]
Hi! I have the same issue. What prefix do you mean?

**Comment by a-markovsky** [comment]
https://github.com/WalletConnect/WalletConnectSwift/issues/68#issuecomment-961284810
this solution may be helpful
