### ISSUE TITLE
Can you update Starscream version please. CocoaPods Conflicts

### ISSUE THREAD

**Issue by ljs19923** [WalletConnect/WalletConnectSwift#91]
<img width="730" alt="Capture d’écran 2021-12-01 à 06 52 42" src="https://user-images.githubusercontent.com/5727223/144229951-4567af65-3cad-4374-9791-fe57e370e0cf.png">

Can you please update Starscream dependency?
Thanks a lot

**Comment by DmitryBespalov** [comment]
Starscream removed from the dependencies.

Fixed in [v1.7.0](https://github.com/WalletConnect/WalletConnectSwift/releases/tag/1.7.0)
