### ISSUE TITLE
"Error Initializing with WalletConnect" from Rainbow app

### ISSUE THREAD

**Issue by ceobitch** [WalletConnect/WalletConnectSwift#93]
Heyo 👋, 

So I cloned your project and ran the Client app. My intent was to connect the Client app to my wallet. **The client app successfully opens up my wallet but nothing show up on regarding to connect to the Client/Example app**. Meaning my wallet does not show a pop up saying "Connect to Example app" Am I doing something wrong or am missing something? 

I'll usually get an error saying " "Error Initializing with WalletConnect" on the rainbow app. 

Kind Regards, 
Ayman 

```
let connectionUrl = walletConnect.connect()

        let deepLinkUrl = "https://rnbwapp.com/wc?uri=\(connectionUrl)"

        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            if let url = URL(string: deepLinkUrl), UIApplication.shared.canOpenURL(url) {
                UIApplication.shared.open(url, options: [:], completionHandler: nil)
            } else {
                self.handshakeController = HandshakeViewController.create(code: connectionUrl)
                self.present(self.handshakeController, animated: true)
            }
        }
```

**Comment by ceobitch** [comment]
FIXED!!!!

So since I was connecting via Rainbow Wallet app.  I had to go into the **### WalletConnect.swift** file and change the return on wcURL inside of the connect function. Specifically, follow these steps: 

1. Go to WalletConnect.swift
2. Change the return value inside of the connect function to:
`return wcUrl.absoluteString.addingPercentEncoding(withAllowedCharacters: .controlCharacters) ?? ""`
3. 🥳
![Screen Shot 2021-12-06 at 8 00 21 PM](https://user-images.githubusercontent.com/65835687/144952514-950321ca-261c-4422-8a0d-d8814c8cbe59.png)

**Comment by tsaievan** [comment]
it still doesn't work
