### ISSUE TITLE
Disconnect session broken updating from 1.6.0 to 1.6.2

### ISSUE THREAD

**Issue by lionel-alves** [WalletConnect/WalletConnectSwift#96]
After update from 1.6.0 to 1.6.2, disconnect session doesn't work anymore, nothing happens for maybe 20 seconds then it finally disconnects with a timeout error in the logs. Reverting to 1.6.0 fixes the issue.

**Comment by DmitryBespalov** [comment]
@lionel-alves thank you for reporting this, I'll take a look.

**Comment by DmitryBespalov** [comment]
Should be fixed in [v1.7.0](https://github.com/WalletConnect/WalletConnectSwift/releases/tag/1.7.0)
